import React, { useState, useEffect } from "react";
import {
  TrendingUp,
  Sparkles,
  RefreshCw,
  Heart,
  Award,
  CheckCircle2,
  Calendar,
  Layers,
  ShieldCheck,
  Zap,
} from "lucide-react";
import type { JournalEntry, PersonalInsightSynthesis, UserProfile } from "../types.ts";
import { requestHolisticInsights } from "../lib/api.ts";
import { savePersonalInsight, fetchUserInsights } from "../lib/firestoreService.ts";

interface InsightsDashboardProps {
  user: UserProfile;
  entries: JournalEntry[];
}

export const InsightsDashboard: React.FC<InsightsDashboardProps> = ({ user, entries }) => {
  const [insights, setInsights] = useState<PersonalInsightSynthesis[]>([]);
  const [synthesizing, setSynthesizing] = useState(false);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);

  useEffect(() => {
    if (user?.uid) {
      fetchUserInsights(user.uid).then((res) => {
        if (res && res.length > 0) {
          setInsights(res);
        }
      });
    }
  }, [user]);

  const latestInsight = insights[0] || null;

  // Compute local mood aggregates
  const moodCounts: Record<string, number> = {};
  entries.forEach((e) => {
    moodCounts[e.mood] = (moodCounts[e.mood] || 0) + 1;
  });

  const totalEntries = entries.length;
  const avgSentiment =
    entries.reduce((acc, curr) => acc + (curr.sentimentScore ?? 0), 0) / (totalEntries || 1);

  const handleSynthesizeJourney = async () => {
    if (entries.length === 0) {
      setStatusMessage("Please write at least one journal entry before synthesizing trends.");
      return;
    }

    setSynthesizing(true);
    setStatusMessage(null);
    try {
      const payload = entries.slice(0, 20).map((e) => ({
        title: e.title,
        mood: e.mood,
        summary: e.reflection?.summary || e.content.slice(0, 200),
        sentiment: e.sentimentScore,
        date: new Date(e.createdAt).toLocaleDateString(),
      }));

      const synthesis = await requestHolisticInsights(payload);
      const fullInsight: PersonalInsightSynthesis = {
        ...synthesis,
        id: "insight_" + Date.now(),
        userId: user.uid,
      };

      await savePersonalInsight(user.uid, fullInsight);
      setInsights([fullInsight, ...insights]);
      setStatusMessage("Holistic synthesis successfully generated by server-side Gemini!");
    } catch (err: any) {
      setStatusMessage("Error: " + (err.message || "Synthesis failed."));
    } finally {
      setSynthesizing(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6 animate-in fade-in duration-300">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl sm:text-2xl font-bold text-slate-100">
              Emotional Journey & Synthesis
            </h1>
            <span className="text-xs font-mono font-medium px-2 py-0.5 rounded-full bg-slate-800 text-teal-400 border border-slate-700">
              Private Analytics
            </span>
          </div>
          <p className="text-xs text-slate-400 mt-0.5">
            Holistic trends and cognitive rhythms synthesized across your isolated reflections.
          </p>
        </div>

        <button
          id="btn-synthesize-insights"
          onClick={handleSynthesizeJourney}
          disabled={synthesizing || entries.length === 0}
          className="flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-teal-600 to-indigo-600 hover:from-teal-500 hover:to-indigo-500 text-white text-xs sm:text-sm font-semibold shadow-md transition-all disabled:opacity-40"
        >
          <Sparkles className={`w-4 h-4 ${synthesizing ? "animate-spin" : ""}`} />
          <span>{synthesizing ? "Synthesizing Patterns..." : "Synthesize Journey Trends"}</span>
        </button>
      </div>

      {statusMessage && (
        <div className="p-3 rounded-xl bg-slate-900 border border-teal-500/30 text-xs text-teal-300 flex items-center justify-between">
          <span>{statusMessage}</span>
          <button onClick={() => setStatusMessage(null)} className="text-slate-400 hover:text-white">✕</button>
        </div>
      )}

      {/* Metric Cards Row */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 space-y-1">
          <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
            Total Reflections
          </span>
          <p className="text-2xl font-black text-slate-100">{totalEntries}</p>
          <span className="text-[11px] text-teal-400 font-mono">Firestore partitioned</span>
        </div>

        <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 space-y-1">
          <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
            Average Sentiment
          </span>
          <p
            className={`text-2xl font-black font-mono ${
              avgSentiment >= 0.1 ? "text-emerald-400" : avgSentiment <= -0.1 ? "text-rose-400" : "text-amber-400"
            }`}
          >
            {avgSentiment > 0 ? "+" : ""}
            {(avgSentiment * 100).toFixed(0)}%
          </p>
          <span className="text-[11px] text-slate-400 capitalize">
            {avgSentiment > 0.2 ? "Positive Baseline" : avgSentiment < -0.2 ? "Heavy / Processing" : "Grounded"}
          </span>
        </div>

        <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 space-y-1">
          <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
            Dominant Mood
          </span>
          <p className="text-2xl font-black text-slate-100 capitalize">
            {Object.entries(moodCounts).sort((a, b) => b[1] - a[1])[0]?.[0] || "None"}
          </p>
          <span className="text-[11px] text-slate-400">Most frequent state</span>
        </div>

        <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 space-y-1">
          <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
            Security Isolation
          </span>
          <p className="text-base font-bold text-emerald-400 font-mono">users/{user.uid.substring(0, 6)}...</p>
          <span className="text-[11px] text-slate-400">Zero log leakage</span>
        </div>
      </div>

      {/* Mood Distribution */}
      <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800 space-y-3">
        <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-400">
          Emotional State Distribution
        </h3>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
          {["peaceful", "grateful", "energized", "reflective", "anxious", "melancholy", "frustrated", "neutral"].map(
            (moodName) => {
              const count = moodCounts[moodName] || 0;
              const pct = totalEntries > 0 ? Math.round((count / totalEntries) * 100) : 0;
              return (
                <div key={moodName} className="p-3 rounded-xl bg-slate-950/60 border border-slate-800/80">
                  <div className="flex items-center justify-between text-xs mb-1.5">
                    <span className="capitalize text-slate-300 font-medium">{moodName}</span>
                    <span className="font-mono text-teal-400">{pct}%</span>
                  </div>
                  <div className="w-full h-1.5 bg-slate-800 rounded-full overflow-hidden">
                    <div className="h-full bg-teal-500 rounded-full" style={{ width: `${pct}%` }} />
                  </div>
                </div>
              );
            }
          )}
        </div>
      </div>

      {/* Latest AI Synthesis Card */}
      {latestInsight ? (
        <div className="p-6 sm:p-7 rounded-2xl bg-slate-900 border border-teal-500/30 shadow-xl space-y-5">
          <div className="flex items-center justify-between border-b border-slate-800 pb-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-teal-500/20 to-indigo-500/20 border border-teal-500/30 flex items-center justify-center">
                <Sparkles className="w-5 h-5 text-teal-400" />
              </div>
              <div>
                <h2 className="text-base font-bold text-slate-100">
                  Gemini Executive Wellness Synthesis
                </h2>
                <p className="text-xs text-teal-400 font-mono">{latestInsight.period}</p>
              </div>
            </div>
            <span className="text-xs px-2.5 py-1 rounded-lg bg-slate-800 border border-slate-700 text-slate-300 capitalize font-mono">
              Trajectory: {latestInsight.overallSentimentTrend}
            </span>
          </div>

          {/* Emotional trajectory */}
          <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 text-xs sm:text-sm text-slate-200 leading-relaxed">
            <span className="text-teal-400 font-semibold block mb-1">Trajectory Narrative:</span>
            {latestInsight.emotionalTrajectory}
          </div>

          {/* Dominant Themes */}
          {latestInsight.dominantThemes && (
            <div>
              <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider mb-2">
                Emerging Core Themes
              </h4>
              <div className="flex flex-wrap gap-2">
                {latestInsight.dominantThemes.map((t, idx) => (
                  <span
                    key={idx}
                    className="px-3 py-1 rounded-lg bg-indigo-500/10 text-indigo-300 border border-indigo-500/20 text-xs font-medium"
                  >
                    #{t}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Strengths & Action Items */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
            <div className="p-4 rounded-xl bg-emerald-950/30 border border-emerald-500/20 text-xs space-y-2">
              <h4 className="text-emerald-300 font-semibold flex items-center gap-1.5">
                <Award className="w-4 h-4 text-emerald-400" />
                Demonstrated Strengths
              </h4>
              <ul className="space-y-1.5 text-slate-300">
                {latestInsight.strengthsIdentified.map((s, idx) => (
                  <li key={idx}>✓ {s}</li>
                ))}
              </ul>
            </div>

            <div className="p-4 rounded-xl bg-teal-950/30 border border-teal-500/20 text-xs space-y-2">
              <h4 className="text-teal-300 font-semibold flex items-center gap-1.5">
                <Zap className="w-4 h-4 text-teal-400" />
                Mindful Growth Recommendations
              </h4>
              <ul className="space-y-1.5 text-slate-300">
                {latestInsight.mindfulActionItems.map((a, idx) => (
                  <li key={idx}>• {a}</li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      ) : (
        <div className="p-8 text-center rounded-2xl bg-slate-900/40 border border-slate-800 space-y-3">
          <Sparkles className="w-8 h-8 text-teal-400 mx-auto" />
          <h3 className="text-base font-semibold text-slate-200">No Journey Synthesis Yet</h3>
          <p className="text-xs text-slate-400 max-w-sm mx-auto">
            Click "Synthesize Journey Trends" above to have server-side Gemini analyze patterns across your entries and distill a holistic trajectory.
          </p>
        </div>
      )}
    </div>
  );
};
